#!/bin/sh

# Download Docker Machine from Github Release, https://github.com/docker/machine/releases

sudo curl -L https://github.com/docker/machine/releases/download/v0.15.0/docker-machine-`uname -s`-`uname -m` -o /usr/local/bin/docker-machine
sudo chmod a+rx /usr/local/bin/docker-machine
