task default: [:install]

@BASHRC = <<END
#!/bin/sh
#
# NOTE: Do **NOT** edit this file.
#   This file is automated generated by cybertk/profile.
#   Edit profile/bashrc instead.

CK_BASHRC_DIR="#{File.dirname(__FILE__)}"
# Source bashrc provided by cybertk/profile
. ${CK_BASHRC_DIR}/bashrc
END

def backup(file)
    backup_file = file
    while File.exist?(backup_file)
        backup_file += ".bak"
    end

    File.rename(file, backup_file)
    puts "Backup #{file} to #{backup_file}"
end

def install_bashrc(file)
    puts "Instaling #{file}"

    file = File.expand_path file

    backup(file)
    File.open(file, 'w') do |f|
        f.write(@BASHRC)
    end
end

task :install do
    install_bashrc('~/.bashrc')
    install_bashrc('~/.bash_profile')
end

task :lint do
    shs = Dir.glob("**/*.sh")
    shs << "bashrc"

    sh "shlint #{shs.join(' ')}"
end
