#!/bin/sh

# TODO: replace with getopt

# Exit if any errors
set -e

main() {
    username="$1"
    password="$2"
    github_repo="$3"

    shift 3
    dots="$@"

    echo "==> Cloning ckdots"
    git clone "https://github.com/cybertk/ckdots" /root/.ckdots

    echo "==> Cloning config"
    git clone "https://$username:$password@github.com/$github_repo" /root/.ckdots/config

    echo "==> Installing ckdots"
    CKDOTS_CONFIG=/root/.ckdots/config /root/.ckdots/bin/ckdots init

    for dot in $dots; do
        /root/.ckdots/bin/ckdots checkout "$dot"
    done
}

main "$@"
